### ISSUE TITLE
TODO: Games that don't allow process hooking can't be recorded with game-capture

### ISSUE THREAD

**Issue by jkluch** [lulzsun/RePlays#10]
Need to implement a secondary capture mode for games like **Counter Strike: Global Offensive**.

Best solution here would be for each game to have a recording method set for it.  Default to game capture, otherwise allow the user to pick another method.

Despite what a lot of the internet says, display capture works and should be fairly performant as it's using the windows desktop duplication api.  The downside to this is OBS's implementation captures the full display so game windows smaller than full screen would show desktop.

Window Capture works as long as the game is not in exclusive fullscreen.

**Comment by Segergren** [comment]
Will be a hard fix. I have tried with "**-allow_third_party_software**" and using a signed **graphics-hook32.dll** and **win-capture.dll** but still no luck.

**Comment by jkluch** [comment]
Game capture doesn't work but display capture should work.  Works in obs.

**Comment by lulzsun** [comment]
I will look into a display capture or even a window capture method for specific games such as CSGO.
