### ISSUE TITLE
Change debug and release npm install to npm ci

### ISSUE THREAD

**Issue by ssc9309** [lulzsun/RePlays#105]
Stay sane by using package lock.

I can do this one myself if you give me perms.

**Comment by lulzsun** [comment]
I see, it would make more sense to use `npm ci`. Either that or lock dependencies in `package.json`. But for now I will change them to `npm ci`. Thanks for pointing this out.

**Comment by lulzsun** [comment]
If you want to make changes yourself next time, I would recommend creating a fork and doing a pull request. But since this change is minor I can do it to save you the troubles.
