### ISSUE TITLE
Improved League of Legends Interfacing

### ISSUE THREAD

**Issue by byotta** [lulzsun/RePlays#108]
Implement LoL game stats to library menu, showing champion, game result, KDA and other stats.

This allows for much quicker reviewing times. See image attachment for an example.

<img width="115" alt="leagueSnip" src="https://user-images.githubusercontent.com/35793449/233806285-03347fbc-7b43-491e-9c11-5a72d1af6ea6.png">

**Comment by lulzsun** [comment]
Completed in #121, available in nightly release, available in next stable release (current release is 1.2.1).

**Comment by byotta** [comment]
Thank you! Looks great
