### ISSUE TITLE
Replays causes stuttering in CS:GO

### ISSUE THREAD

**Issue by Segergren** [lulzsun/RePlays#133]
When utilizing OBS Studio's Display Capture, everything runs smoothly with zero stutters. However, using Replays results in significant stuttering. Despite changing to identical settings that should theoretically yield similar FPS, this issue persists. I've spent the last two days trying to fix this issue, but I'm still looking for a solution.
![image](https://github.com/lulzsun/RePlays/assets/58270063/2a75a628-3058-419f-8f50-5a8b9fec1235)

**Comment by Iovebug** [comment]
Also experiencing this. Replays will crash during a CSGO session then restart multiple times each time it fails.

What resolution are you using? Wondering if it has something to do with forced resolution? I play 4:3 1280x1040

**Comment by Segergren** [comment]
> What resolution are you using? Wondering if it has something to do with forced resolution? I play 4:3 1280x1040

Currently using 2560x1440 :)
I really hope CS2:s anti-cheat will allow us to use Game Capture instead of Display Capture

**Comment by Segergren** [comment]
I'll close this for now. Works OK when using vSync in CS2.
