### ISSUE TITLE
Support for CS2 recording

### ISSUE THREAD

**Issue by ArnoldBraine** [lulzsun/RePlays#144]
Currently CS2 games are not being recorded, is there already a known workaround? hopefully this would be an easy fix!

**Comment by Segergren** [comment]
This is a known issue and CS2 has blocked us and OBS from using Game Capture. There is currently no known way to capture it without using Display Capture (which is pretty bad)

**Comment by m8nu** [comment]
Does it work with **-allow_third_party_software** ?

**Comment by ArnoldBraine** [comment]
@m8nu This won't start CS2 in trusted mode which means you won't be able to play on VAC secured servers (AKA the whole game)

**Comment by ArnoldBraine** [comment]
Won't be recording much highlights getting headshotted by cheaters spinning around 😆

**Comment by Segergren** [comment]
I tried it an it completely destroyed my Trust Factor for months :(

**Comment by ArnoldBraine** [comment]
Yeah i wouldn't recommend doing so, maybe there could be like a "experimental features" checkbox where you would enable screencapture instead of gamecapture for CS2? Would it just be bad quality or really hit the hardware? because if you have the hardware to throw at it, it think that would be a nice temporary "solution"

**Comment by jkluch** [comment]
> Yeah i wouldn't recommend doing so, maybe there could be like a "experimental features" checkbox where you would enable screencapture instead of gamecapture for CS2? Would it just be bad quality or really hit the hardware? because if you have the hardware to throw at it, it think that would be a nice temporary "solution"

In my experience I've noticed negligible performance difference in obs using display capture vs game capture.  Sure, technically there are performance gains going the game capture route.. but realistically I don't think they matter that much.  Maybe on a very low end machine.  The only actual issue with display capture is games running in fullscreen exclusive mode don't get captured properly.

I'm not really a fan of display/game capture being a global option either though.  IMO it should default to game capture with the ability to override to display capture per game.  Ideally RePlays would ship with some prebaked overrides included for games known to conflict with game capture like Counter Strike and Rainbow 6 Siege.

**Comment by Segergren** [comment]
#148 Has added support for CS2 recording
#150 Has added CS2 integrations (automatic kill bookmarks)

**Comment by Segergren** [comment]
Should be fixed now in latest 1.2.45.
Can you verify @ArnoldBraine?

**Comment by ArnoldBraine** [comment]
Hi there :)

Can confirm it works for me and another friend! Great work, one small detail. 
Not sure how easy it is to detect whether someone is playing another resolution, but i play 4:3 so my game looks like ![this](https://github.com/lulzsun/RePlays/assets/25790947/13bba9a9-b6b5-4ad6-b503-6e12cfeac099)
Would it be alot to check the resolution and stretch it afterwards to native?
If it is too much work, don't bother 😄 

KR,
Arnold

**Comment by RavenStryker** [comment]
> Would it be alot to check the resolution and stretch it afterwards to native?
> If it is too much work, don't bother 😄

Why would you want to stretch a 4:3 replay/clip into something different? They can't magically add game footage where it doesn't exist so everything would look oddly out of proportion and skewed really wide if that took place. Unless I'm misunderstanding what you mean by the quoted piece above.

**Comment by ArnoldBraine** [comment]
Okay so basically:
- My game itself is 4:3 resolution stretched to native (screen is 16:9) aka i have no black bars
- Recording comes out to 4:3 with black bars
- What i would like to propose: clip that could be stretched to native, either when recorded (with a setting in the menu) or in the editor (so you can select stretch to 16:9)

**Comment by Segergren** [comment]
@ArnoldBraine Can you send me a log file of when you start and end a CS2 recording?

**Comment by ArnoldBraine** [comment]
@Segergren, which type of log file am i looking for? + noticed one more thing, the automatic kill bookmarks, does that already work? (https://github.com/lulzsun/RePlays/pull/150 Has added CS2 integrations (automatic kill bookmarks))

**Comment by lulzsun** [comment]
@ArnoldBraine If you navigate to Settings > Help, you should be able to locate the logs file for us. 

And yes, it should be possible to stretch-to-fit the video as a setting option.

**Comment by ArnoldBraine** [comment]
I extracted from start to finish of a session
[extract_log.txt](https://github.com/lulzsun/RePlays/files/13047138/extract_log.txt)

**Comment by Segergren** [comment]
Can you create a new feature request so we close this issue @ArnoldBraine?

**Comment by Segergren** [comment]
@lulzsun Can you close this issue?

**Comment by lulzsun** [comment]
Closing this issue.
