### ISSUE TITLE
Replays causes stuttering in COD (Warzone 2)

### ISSUE THREAD

**Issue by daNutzzzzz** [lulzsun/RePlays#145]
Suffering consistent and frequent freezing/stuttering/FPS drops when Replays is running. if i quit Replays the issue stops.

```
Win11 (10.0.22621.2361)
Nvidia RTX 4070 (latest Drivers)
AMD 5950x
32Gb RAM
NVMe M.2 PCI-E Gen 4
```

**Comment by lulzsun** [comment]
Closing this issue as it may have been resolved by numerous changes by update 1.3.0, if this still isn't resolved, feel free to add more detail and we can reopen this issue.
