### ISSUE TITLE
No Sound Capture

### ISSUE THREAD

**Issue by TheSparky23** [lulzsun/RePlays#147]
During Game Capture there is no sound, I've tried changing to multiple outputs and still nothing on the captures. Any ideas

**Comment by TheSparky23** [comment]
I was able to get sound in capture by plugging in a headset and selecting a new device, but still no recording on other devices

**Comment by lulzsun** [comment]
If you could please provide logs, it could help us better debug the issue.

**Comment by lulzsun** [comment]
Closing this issue as it has gotten stale and may have been resolved by the numerous changes in update 1.3.0 and in the new nightly release. 

But if this still isn't resolved, feel free to add more detail and we can reopen this issue.
