### ISSUE TITLE
Final Fantasy XIV does not stop recording after exitting out of game

### ISSUE THREAD

**Issue by Austin-Chau** [lulzsun/RePlays#153]
When closing out of the game, RePlays doesn't stop recording, and thinks the game is still running. I've checked the running processes and it is not running there. If I boot the game for a very short period (<1 minute) then it will record, but the recordings are usually very laggy and choppy. Other games record just fine. If I kill RePlays then the file becomes unreadable.

**Comment by lulzsun** [comment]
Feel free to provide the logs file here so we can try to take a better look at the issue.

**Comment by Austin-Chau** [comment]
I did not realize there were logs! I've provided a log when it just happened. I didn't realize it but it might also be happening in runelite. I switched to nightly build so this is a log from the nightly build, but it's still the same issue.
[logs.txt](https://github.com/lulzsun/RePlays/files/13185372/logs.txt)

**Comment by lulzsun** [comment]
Closing this issue as it has gotten stale and may have been resolved by the numerous changes in update 1.3.0 and in the new nightly release. 

But if this still isn't resolved, feel free to add more detail and we can reopen this issue.
