### ISSUE TITLE
Issue recording osu! on both Stable and Nightly release (V1.2.45)

### ISSUE THREAD

**Issue by ohkiba** [lulzsun/RePlays#155]
So for the past couple of months I've had this issue where the software doesn't record or even detect osu! properly. On all the other games I play it seems to work perfectly fine.

On the stable release, it would fail to do a game capture so it would default to display capture which I think is fine by itself, but whenever I alt-tab to another window usually on my other monitor, sometimes it seems to go to a black screen, and the screen does not change even after I tab back in to osu.

On the nightly release, it wouldn't even recognize osu!, reporting the window with a weird resolution like 1920x1081. I've tried changing the resolution and going from borderless to fullscreen but it still fails to detect. I also tried to add that force display capture option in the gameDetections for osu! but nothing changed.

I've also tried this on another PC using 1 monitor with fresh installs of both RePlays and osu! but I still get the same issue.

I've attached logs for both Stable and Nightly, as well as the video that corresponds to the Stable logs.

[RePlaysOsu1.2.45.txt](https://github.com/lulzsun/RePlays/files/13232661/RePlaysOsu1.2.45.txt)
[ReplaysOsu1.2.1.txt](https://github.com/lulzsun/RePlays/files/13232662/ReplaysOsu1.2.1.txt)
https://youtu.be/HR1bs7sowR8 (Bug happens around 5:26, video comes back at 11:28)

**Comment by lulzsun** [comment]
Hi, sorry for the late response. Just recently started to pickup development again.

Have you tried whitelisting `osu!.exe` as a temporary fix? Any executable added to the whitelist should ignore "invalid" resolutions.

I will be redesigning the window detection mechanisms in the future, it seems that the current solution in nightly has been giving similar issues for other users.

**Comment by ohkiba** [comment]
Just checked out the latest nightly release with osu!.exe whitelisted and it seems to be working perfectly now, consistently starts the capture and so far there's no black screen issues. Thanks for the fix :)
