### ISSUE TITLE
GTA V and CS 2 not recording

### ISSUE THREAD

**Issue by bjorn278** [lulzsun/RePlays#157]
Added them to manual detection still not working pls fix. Or extend manual recording possibilities

**Comment by Segergren** [comment]
Please provide your logs.

**Comment by bjorn278** [comment]
[logs.txt](https://github.com/lulzsun/RePlays/files/13417902/logs.txt)
Apparantly the gtav window has an invalid resolution of 1914x1052. Any way to fix this? my ingame settings are 1920x1080 fullscreen

**Comment by lulzsun** [comment]
For GTAV, it seems like you added the wrong executable for the whitelist. If you add `GTA5.exe`, it should ignore the invalid resolution issue.

**Comment by lulzsun** [comment]
Closing this issue as it may have been resolved, if this still isn't resolved, feel free to add more detail and we can reopen this issue.
