### ISSUE TITLE
No thumbnails after refresh

### ISSUE THREAD

**Issue by Segergren** [lulzsun/RePlays#166]
The images do not appear after a refresh or deletion of a video. The logs don't reveal any issues, however, the console does provide some information.

**Version:** 1.2.55

![image](https://github.com/lulzsun/RePlays/assets/58270063/a2f6f744-f197-46a0-a6b6-d54eb1fb74bf)

![image](https://github.com/lulzsun/RePlays/assets/58270063/786ca5c4-4e16-4d6d-a4f4-8af1c91d1d11)

**Comment by Segergren** [comment]
Instead of looking at
**file:///S:/Videos/Counter-Strike%202/.thumbs/2023_12_15_21_05_38-ses.webp**
It looks at
**http://localhost:3001//Counter-Strike%202/.thumbs/2023_12_15_21_05_38-ses.webp**

**Comment by lulzsun** [comment]
Pushed a fix, let me know if the issue still exists after the next nightly build.

**Comment by Segergren** [comment]
Perfect, thanks for the fix @lulzsun
