### ISSUE TITLE
White screen on exporting clip

### ISSUE THREAD

**Issue by MrMK0R** [lulzsun/RePlays#167]
During the saving process, of a clip, the screen will flash white before you can click the "confirm" button.

Steps to reproduce:

```
1: Record Gameplay
2: Click Session
3: Click recorded video
4: Create Clip
5: Export Clip
``` 
 Specs:
```
 Windows 11
 Ryzen 7 2700x
 GTX 1070
```

![2024-01-04 03-19-58](https://github.com/lulzsun/RePlays/assets/112554159/422d5585-785e-4b0c-9a7d-901681a9aedf)

**Comment by lulzsun** [comment]
Hi, I was unable to reproduce this issue. 

Currently, the front end does not log any errors to the log.txt file. If you experience this white screen issue again, could you open up the dev tools by pressing Ctrl+Shift+I, and taking a screenshot of anything that appears significant or related to the issue in the developer console? (warnings, errors, debug messages)

**Comment by MrMK0R** [comment]
Hey @lulzsun,

Here is the error log of when the white screen happens.
![image](https://github.com/lulzsun/RePlays/assets/112554159/b3f9dfb0-9b28-4e7e-8589-ba41d23d0091)

**Comment by lulzsun** [comment]
It looks like you're using the nightly release. I was able to replicate this issue on version 1.2.55, but not on version 1.2.56. This version was released a couple hours ago so maybe it hasn't applied for you yet.

Can you make sure that you're on the latest nightly release?

**Comment by MrMK0R** [comment]
That seems to have fixed the issue, however now I cannot select my GPU as the encoder only software. Do you want me to create another issue for it?
![image](https://github.com/lulzsun/RePlays/assets/112554159/1980c63b-e3de-445a-80b8-7687a1f30836)

**Comment by Segergren** [comment]
Hi @MrMK0R , I believe it's a good idea to open a new issue about this. I've encountered it before (following updates?). I debugged it a while ago and I noticed that OBS seems to indicate that only Software (x264) is available.

**Comment by lulzsun** [comment]
Glad to hear that the initial issue was fixed.

For the new issue, I did notice this after a fresh debug build on Windows. I have pushed a potential fix for it and will manually run a nightly build for it after sending this comment. 

If the new nightly release still doesn't fix the problem, feel free to create a new issue for it.
