### ISSUE TITLE
Bookmark button not saving bookmarks when recording is finished.

### ISSUE THREAD

**Issue by MrMK0R** [lulzsun/RePlays#169]
I am not sure if this is the intended use for the bookmark feature, but when recording, and hitting the bookmark shortcut, the bookmark doesn't show in the video.

Steps:
``
1 - bind bookmark button and enable bookmarks
``
``
2 - start game with recording
``
``
3 - make a play and hit bookmark button
``
``
4 - end recording
``
``
5 - Bookmarks added during recording don't show in video preview.
``

**Comment by Segergren** [comment]
Can you attach the logs?

**Comment by MrMK0R** [comment]
Here is current log
[logs.txt](https://github.com/lulzsun/RePlays/files/13863102/logs.txt)

**Comment by lulzsun** [comment]
It looks like it properly registers the keybind on press, so this issue might be related to how we are currently storing bookmarks in localStorage of the WebView.

If we complete #84, this may solve the issue. I might get around doing that soon, but no promises.

**Comment by lulzsun** [comment]
This issue should be fixed by https://github.com/lulzsun/RePlays/commit/eb78b562cd4071e45270083a59752387bae9e5b5

Will still be looking to move bookmarks/metadata out of local storage.

**Comment by Segergren** [comment]
Nice find @lulzsun!
