### ISSUE TITLE
BUG: weird bookmark behavior when deleting

### ISSUE THREAD

**Issue by jkluch** [lulzsun/RePlays#19]
Needs investigation.. I noticed when trying out bookmarks if I made more than one, then deleted one.. all of them disappeared.

If I then go and add some more and delete one.. all of the new ones go away but it seems like some of the old ones show up again.

**Comment by Segergren** [comment]
I will take a look at it today. Pretty strange behavior since it was working fine and we haven't made any changes to it.

**Comment by lulzsun** [comment]
I noticed this unintentional behavior right after accepting your pull request (I did not mention it earlier because it wasn't really a major issue), so I'm assuming it is your implementation that is the problem and not any other related commits after.

**Comment by lulzsun** [comment]
I would take over this issue for you but my priorities are currently in the backend of the project. Just let me know if you run into any issues and I can help you sort it out.

**Comment by Segergren** [comment]
> I noticed this unintentional behavior right after accepting your pull request (I did not mention it earlier because it wasn't really a major issue), so I'm assuming it is your implementation that is the problem and not any other related commits after.

Okay. I'll take a look at it right now.
