### ISSUE TITLE
Allow contributions to the wiki

### ISSUE THREAD

**Issue by sshcrack** [lulzsun/RePlays#194]
I've just noticed that the link and the version of the .NET SDK are outdated in the [wiki](https://github.com/lulzsun/RePlays/wiki/Development:-Windows). It *should* be **8.0.100** but actually it mentions .NET SDK **7.0.200**. The folder `- bin\Debug\net7.0-windows` is outdated as well.
Furthermore, the command to clone the repository is missing the `--recursive` flag.

As there is no way to create a pull request for the wiki, I'm submitting this one as an issue.

If you want to, take a look at [Create pull requests for your GitHub Wiki](https://nimblehq.co/blog/create-github-wiki-pull-request) so contributions can be made to the wiki as well.

**Comment by lulzsun** [comment]
I have updated wiki to reflect the current state of the project.

I'll be looking into allowing contributions to the wiki. Thanks for letting me know about this!

**Comment by lulzsun** [comment]
I finished setting up the necessary GitHub workflow and actions to allow contributions to the wiki by making a pull request with changes to the files located here: [.github/wiki](https://github.com/lulzsun/RePlays/tree/main/.github/wiki)

Closing this issue as complete.
