### ISSUE TITLE
Repository not cloneable

### ISSUE THREAD

**Issue by sshcrack** [lulzsun/RePlays#197]
When cloning this repository on a windows machine following error occurrs:
```bash
error: invalid path '.github/wiki/Development:-Getting-Started.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```
This happens because the `.github/.wiki` has files which have a colon in their filenames (e.g. `.github/wiki/Development:-Getting-Started.md`).

**Comment by lulzsun** [comment]
Thanks for looking into this! I haven't touched a Windows environment in a while so I forgot about this. Closing as it is fixed.
