### ISSUE TITLE
Add options for advanced users.

### ISSUE THREAD

**Issue by hl2jeep** [lulzsun/RePlays#209]
I love this tool and it works really well however as someone who knows their way around obs there's a few feature I would really like to see implement.
1. Codec selection, I like to record using AV1 because my GPU supports it and it use less space
2. Custom bitrate

**Comment by lulzsun** [comment]
Basic interface rate control options have been implemented and will be available in the nightly release (and next stable 1.3.1+). Closing this issue as completed.
