### ISSUE TITLE
Some games never stop recording with no way to stop it.

### ISSUE THREAD

**Issue by hl2jeep** [lulzsun/RePlays#215]
I've encountered a few games such as Minecraft that continue to record even after the game is closed, the recording shortcut (ctrl + f9) doesn't seem to work either, even when I change the binding.

**Comment by lulzsun** [comment]
Feel free to attach log files here so we can try to debug the issue.

You can find these logs by going to Settings > Help > Show logs.

**Comment by AirplanegoBrr** [comment]
I think I am having the same problem, I am MASHING my `r` key and its REFUSING to stop the recording. (even just pressing the `r` key once doesn't fix it`)
[logs.txt](https://github.com/user-attachments/files/16537730/logs.txt)

**Comment by lulzsun** [comment]
@AirplanegoBrr Could you try using the nightly version instead? There has been some improvements related to this which have not yet been pushed as a stable version.

**Comment by Segergren** [comment]
Can we close this?

**Comment by AirplanegoBrr** [comment]
> Can we close this?

Yes, sorry life got busy

**Comment by lulzsun** [comment]
I've had this issue occur recently even after a few attempts at fixing it but it seems to be a very rare issue where the LibObsRecorder fails to stop for an unknown reason (even after calling a force-stop).

However, I will close this issue anyways and we can always open another issue later down the line if we can properly pinpoint the issue.
