### ISSUE TITLE
BUG: Big performance hit when tabbing in.

### ISSUE THREAD

**Issue by Segergren** [lulzsun/RePlays#22]
I usually get 180-220 fps while recording. The fps goes down to 100-130 after tabbing in.
Game: League of Legends but should be for all games.

**Comment by sonicv6** [comment]
This will be due to using software encoding.

**Comment by sonicv6** [comment]
Possibly fixed by #25

**Comment by Segergren** [comment]
> 

Might have. I don't have any FPS issues on hardware encoding.

**Comment by sonicv6** [comment]
I would expect the issues before to be the software encoding hammering your processor and bottlenecking.

**Comment by Segergren** [comment]
Will close this since I haven't been able to reproduce it.
