### ISSUE TITLE
Not capturing audio from Discord / in-game voice?

### ISSUE THREAD

**Issue by kmanc** [lulzsun/RePlays#225]
I don't know exactly when this started but it seems like it was a relatively recent thing. I'm running version 1.3, but I also tried the nightly build and this seems to still be the case. I've toggled and changed every capture setting I can think of but I still only get game audio + my mic; any thoughts?

**Comment by sonicv6** [comment]
Are you using headphones which have a separate audio device in Windows for communication?

**Comment by kmanc** [comment]
> Did you play the video through `Windows Media Player Legacy`? I had the same issue, but when I used VLC or another application, all sounds worked fine.

This seems to persist on other applications, and in the RePlays app's player itself

> Are you using headphones which have a separate audio device in Windows for communication?

I am, but I've added it as an "Input Device" under the "Capture" settings. Also worth noting is that none of the comms from teammates in Discord comes through

**Comment by sonicv6** [comment]
You would have to add the communication device as an output device as well to capture Discord audio. Could you upload a log file as well please?

**Comment by kmanc** [comment]
I'll try re-adding the communication devices and see what happens. Will attach a log later if the issue persists

**Comment by kmanc** [comment]
Re-adding all of my communication devices seemed to do the trick. Sorry about that y'all
