### ISSUE TITLE
Feature: Youtube uploader

### ISSUE THREAD

**Issue by hl2jeep** [lulzsun/RePlays#227]
Add the option to upload directly to youtube, an app you can use to base this off is ShareX because it's also open source and already has the youtube uploader so you can simply reuse theirs. the options for the upload should be similar to how it works in shareX, where you can input a title, description and video visibility.

**Comment by Segergren** [comment]
Thank you for the suggestion! This feature has already been requested in #129. Feel free to follow that thread for updates.

**Comment by lulzsun** [comment]
Closing this since it is a duplicate issue.
