### ISSUE TITLE
EasyAntiCheat Window Exclude List

### ISSUE THREAD

**Issue by Bmilner88** [lulzsun/RePlays#239]
Games that utilize EasyAntiCheat will start the recording when the EAC window appears and won't record the game itself.

Example Video:
https://github.com/user-attachments/assets/cb1a4c80-9872-44cc-9112-b4a7db3a7e41

Adding the EAC .exe to the local exclude list doesn't work either, it causes RePlays to not even start the recording for the game itself:
![image](https://github.com/user-attachments/assets/dba43a2e-332a-438b-953b-798593355fcc)

Full Logs:
[logs.txt](https://github.com/user-attachments/files/17513675/logs.txt)

Please let me know if you need any other information :)

**Comment by lulzsun** [comment]
`start_protected_game.exe` has been added to the global `nonGamesDetection.json` list. Could you verify if the issue still occurs or not?

**Comment by Bmilner88** [comment]
I tested Apex and it seems to be working! Thank you!
