### ISSUE TITLE
Bug: Local recordings directory doesn't change consistently

### ISSUE THREAD

**Issue by ssc9309** [lulzsun/RePlays#33]
- New install
- Changed the Game Recordings Directory under Settings -> Upload -> Local Folder
![image](https://user-images.githubusercontent.com/5625097/192117505-d5dedd52-e9cd-40c9-926d-a663225d2995.png)
- Navigate to Settings -> Storage
![image](https://user-images.githubusercontent.com/5625097/192118026-b0266cf4-6dc2-4bbf-9abb-8c52c399d2b1.png)

- Game Recordings Directory still shows the previous folder location.
  - When clicking on the location text, it will popup a windows folder select window with the NEW location
  - When clicking on the Open Folder button, it will open the windows file explorer of the PREVIOUS location.

After gameplay:
- The game was recorded to the old location (the location shown in Settings -> Storage not Settings -> Upload -> Local Folder)

After restarting the software:
- UI still behaves the same way as before.
  - Game Recordings Directory under Upload -> Local Folder and Storage are different
  - Clicking on the location address under Storage navigates me popup to the location shown in Upload -> Local Folder
  - The game is still recorded to folder written in Storage

Expected Behavior:
- Either
  1. The Game Recordings Directory should be consistent in both Upload -> Local Folder and Storage
  2. or they should be written differently and the functionality shouldn't bleed into one another.

**Comment by ssc9309** [comment]
I really appreciate you @lulzsun for continuing this project!
I've been following for years. Let me know how I could help.

Thanks!

**Comment by Segergren** [comment]
I understand what you mean. The title over Local Folder should be "Local Folder Directory" or something like that, not "Game Recordings Directory". I think the feature is there to make it possible upload to a Network drive etc.

**Comment by sonicv6** [comment]
Yeah, they're not equivalent settings, the one under Upload is for long-term storage to ensure recordings don't ever get deleted.

**Comment by ssc9309** [comment]
Thanks for the explanations!
Then it would make most sense to me as a user if the names of those two are different and clicking on the location text on Save Locations panel opens what it says instead of address in Upload -> Local Folder

**Comment by sonicv6** [comment]
What location it displays when you click the text is just handled by the windows dialog system, (it's just the last selection you made) if you want to browse the folder in Save Locations, click the button instead

**Comment by sonicv6** [comment]
I will rename the setting though

**Comment by ssc9309** [comment]
> 

Ah I see. It has nothing to do with the app.
Thanks for the clarification!

**Comment by Segergren** [comment]
Removed "Game Recordings Directory" in the Upload tab since it didn't make sense #36.
Is this enough or do you want us to do something else to close the issue?

**Comment by ssc9309** [comment]
Looks great. Thanks!
