### ISSUE TITLE
Feature Request: Downmix to Mono

### ISSUE THREAD

**Issue by ssc9309** [lulzsun/RePlays#35]
RePlays is recoding the mic sounds only in left ear when using Scarlett Solo.

I know very little about the audio engineering (?). I found a video better explaining the situation that I'm experiencing https://youtu.be/CfGZyTAfd1c?t=352

Maybe Discord-like behavior is preferred by default https://twitter.com/discord/status/853281035341135877?lang=en
They auto downmix to mono.

Thanks!

**Comment by sonicv6** [comment]
This is caused by a mic outputting a stereo signal and only using one channel, I'm not certain how you'd set recording to Mono in LibObs but I'll have a look into it

**Comment by lulzsun** [comment]
I created a commit addressing this issue, please test and confirm that it is working once the commit makes it to the nightly release. (Nightly release will be updated at 12:00am PST)

**Comment by ssc9309** [comment]
Confirmed. Downmix to mono feature in nightly release 125 works beautifully.
Thanks!

**Comment by lulzsun** [comment]
No problem, cheers!
