### ISSUE TITLE
Video duration label

### ISSUE THREAD

**Issue by ssc9309** [lulzsun/RePlays#42]
Goal:
- Show the duration of the videos on the Sessions panel. See attached for a dank mockup.
![image](https://user-images.githubusercontent.com/5625097/192715859-3e3ea24e-c26e-4409-9750-1112e487c57b.png)

Purpose:
- It's niceu to see video durations.

**Comment by lulzsun** [comment]
Feature has been added should take effect in the next nightly build. Thanks for requesting this feature!

**Comment by ssc9309** [comment]
Just tested it. Looks great! Thank you.
