### ISSUE TITLE
Language localization

### ISSUE THREAD

**Issue by lulzsun** [lulzsun/RePlays#5]
Implement localization for user interface.

- https://www.npmjs.com/package/react-localization
- https://www.npmjs.com/package/react-intl
- https://www.npmjs.com/package/react-i18next

**Comment by swyknox** [comment]
I'm working on internationalization support with react-i18next.
Once you complete the changes, we'll talk about some changes, see you later!

![image](https://github.com/lulzsun/RePlays/assets/52772425/1850a6e1-05af-46a7-a907-a51bfc516237)

**Comment by swyknox** [comment]
Hi @lulzsun, first of all I've to say that RePlays is amazing!

I've implemented react-i18next and integrated support for multiple languages: de, en, es, fr, it, pt, and ru, just part of the initial testing phase.

Initially, the language detection and automatic switching worked smoothly while I was working on the ClientApp. However, as I added more languages, I encountered problems with the frontend, which ended up displaying a blank interface.

As I'm currently using a web-based setup, I couldn't dive deeper or compile for debugging purposes, nevertheless I added translation keys everywhere I identified text input. I'd be grateful if you could review the code for possible issues. If possible, could you also provide an artefact/exe for analysis. This would allow me to thoroughly examine the current translation system and improve it to ensure compatibility with the main branch

Thanks for your attention to this matter. I eagerly await your response and any updates!

https://github.com/swyknox/RePlays/tree/internationalization

**Comment by lulzsun** [comment]
Hey, thanks for looking into this!

I see you've put in a lot of work so far and I would love to help. If you can create a pull request, I can give it a review and help tackle the problems you are encountering.

**Comment by Segergren** [comment]
This can be closed, right? :)
