### ISSUE TITLE
BUG: High GPU-usage while not recording

### ISSUE THREAD

**Issue by Segergren** [lulzsun/RePlays#53]
I don't know if it's a bug in RePlays or the task manager.
I've realized that task manager indicates that RePlays uses a lot of GPU usage.
HWMonitor shows otherwise and very low GPU usage (which I think is correct since the fans don't spin up).

https://user-images.githubusercontent.com/58270063/195988372-f53e9f37-f7f7-4cdd-a37e-6e57d49e4bc2.mp4

**Comment by sonicv6** [comment]
Is this consistently reproduceable or just happened once?

**Comment by Segergren** [comment]
@sonicv6 Happens consistently directly after opening the application. 
Can you reproduce it (1.0.47)?

**Comment by sonicv6** [comment]
I can't install the app at all for some reason
