### ISSUE TITLE
Clicking on Change logs doesn't do anything

### ISSUE THREAD

**Issue by ssc9309** [lulzsun/RePlays#67]
Problem:
- clicking on the Change logs button doesn't seem to do anything.
![image](https://user-images.githubusercontent.com/5625097/200205958-1db08747-8840-479a-ba6e-c8a2091841ef.png)

Expected Behaviour:
- Either open the release page on github or show the changes in the app via a new page / popup.

**Comment by lulzsun** [comment]
Change logs button has been removed in favor of a Check for Updates / Update button. Closing this issue.
