### ISSUE TITLE
Replays deleted whenever I reboot my computer

### ISSUE THREAD

**Issue by Saypond** [lulzsun/RePlays#81]
Happened after I changed my video saved folder to my new SSD. Completely removed RePlays and reverted save location to default location on C drive. Still same issue.

**Comment by Segergren** [comment]
Hi, do I understand correctly that the whole application (not the videos) got deleted?
Can you share a log file? (Settings -> Help -> Show logs -> logs.txt)

**Comment by Saypond** [comment]
Ah of course right when I uninstall it again it of course works fine now. Here's the log dump if you still need it.

________________________________

**Comment by Segergren** [comment]
I think you can close this one and open it again if another user experiences the same issue. I can't find anything strange in the logs @lulzsun
