### ISSUE TITLE
Guild Wars 2 recording with incorrect resolution

### ISSUE THREAD

**Issue by YaminoNakani** [lulzsun/RePlays#83]
Game, Guild Wars 2, is recorded in the wrong aspect ratio regardless of resolution settings.
![image](https://user-images.githubusercontent.com/29808496/221487774-1c4bd3a1-b1fc-40e7-9afc-6c3ae4c5633a.png)

**Comment by lulzsun** [comment]
Does the game happen to show a splash screen before loading the game? Might be related to #39 if so.

**Comment by lulzsun** [comment]
Closing this issue to de-clutter the number of open issues. Will be tracking this issue in #39.
